### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by socialwarespace** [VotePen/VotePen#33]
With any API request
"Oops, something went wrong."

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api/users/profile
api/users/account
api/submission

etc.

**Comment by YoginthS** [comment]
Please elaborate the issue, where did you find this?

**Comment by YoginthS** [comment]
We'll Close this issue after 24 hours, because of lack of information!
